### ISSUE TITLE
calendar-vertical can show two month in one screen

### ISSUE THREAD

**Issue by dongchong** [airbnb/HorizonCalendar#214] opened 2023-02-16 12:05 UTC
very thanks this lib , is best.
bug now, in horizontal screen, we need show two month,
and calendar is vertical scroll.
can you help me how to implement it？
very thank you
![image](https://user-images.githubusercontent.com/11833020/219360313-f114fa67-82f4-4af5-9323-9ea046335429.png)

**Comment by bryankeller** [comment] 2023-02-22 05:19
Can you post a video of the intended behavior? I don't understand the screenshot.

**Comment by bryankeller** [comment] 2023-02-22 21:12
I see! Thanks for explaining.

Sorry, but there is no plan to support this behavior. Closing as won't fix. Good luck finding an alternative solution!

**Closed by bryankeller** 2023-02-22 21:12 UTC
